### ISSUE TITLE
arXiv TOS

### ISSUE THREAD

**Issue by jradavenport** [bmorris3/synXiv#1]
Love the idea of aiding in curation (would also love to see improved tools available for voxcharta)

Note of caution: arXiv takes automated scraping seriously. Just be sure you don't violate their [terms of service](http://arxiv.org/help/robots)

**Comment by bmorris3** [comment]
By my read of the TOS, they're concerned about indiscriminate downloads of the whole server. This tool effectively acts as a replacement web browser – it presents the [list/astro-ph.EP/new](http://arxiv.org/list/astro-ph.EP/new) page in the terminal, and allows the user to select which papers to download. It doesn't encourage downloads at a pace any more rapid than the average presenter at a journal club is likely to do, but I agree, it's worth clarifying. 

I've sent an email to the arXiv moderators, and I'm waiting to see what they say before I clean up the code and deploy it (read: tweet about it).

**Comment by bmorris3** [comment]
They agreed with my interpretation, as long as we're not crawling the arXiv, we're good.

**Comment by jradavenport** [comment]
Excellent! Can't wait to see a demo of this package in action!
